urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'taskmaster'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.TaskFormView.as_view(), name='form'),
    path('new/', views.new_task, name='new'),
    path('save/', views.save_task, name='save'),
    path('<int:pk>/toggle/', views.toggle, name='toggle'),
    path('purge/', views.purge, name='purge'),
    path('register/', views.register_request, name='register'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
    path('password_reset', views.password_reset_request, name='password_reset'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('taskmaster:password_reset_complete'), template_name="taskmaster/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
]

templates/taskmaster/graphic.html
{% extends "taskmaster/header.html" %}

{% block content %}

{% if user.is_authenticated %}
<div id="body">
    <div class="column high">
        <h1>Very Urgent!</h1>
        {% for task in high_urgency %}
        {% include "taskmaster/tasks.html" %}
        {% empty %}
        <h2>No tasks</h2>
        <div class="task" style="visibility: hidden;"></div>
        {% endfor %}
    </div>
    <div class="column medium">
        <h1>Urgent</h1>
        {% for task in med_urgency %}
        {% include "taskmaster/tasks.html" %}
        {% empty %}
        <h2>No tasks</h2>
        <div class="task" style="visibility: hidden;"></div>
        {% endfor %}
    </div>
    <div class="column low">
        <h1>Not Urgent</h1>
        {% for task in low_urgency %}
        {% include "taskmaster/tasks.html" %}
        {% empty %}
        <h2>No tasks</h2>
        <div class="task" style="visibility: hidden;"></div>
        {% endfor %}
    </div>
    <div class="links">
        <div id="new" class="button navigation" onclick="show_new();">
            <div class="label normal_text">Add New Task</div>
        </div>
        <a class="buttonlink" href="{% url 'taskmaster:purge' %}" onClick="return confirm('Are you sure you want to delete these tasks?');">
            <div id="purge" class="button navigation">
                <div class="label normal_text">Delete Completed Tasks</div>
            </div>
        </a>
        <a class="buttonlink" href="{% url 'taskmaster:logout' %}">
            <div id="logout" class="button navigation">
                <div class="label normal_text">Logout</div>
            </div>
        </a>
        <div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-dark{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <div id="new_task" class="backdrop">
        <div class="detailcontainer">
            <form action="{% url 'taskmaster:save' %}" method="POST">
                <div id="detail" class="detail medium">
                    <input type="text" class="task_input full_width" id="short_desc" name="short_desc" placeholder="Title" required>
                    <input type="date" class="task_input full_width no_bottom" id="due_date" name="due_date">
                    <input type="time" class="task_input full_width" id="due_time" name="due_time">
                    <select class="task_input no_bottom full_width" name="importance" id="importance" onChange="change_importance('');">
                        <option value="0">Low Importance</option>
                        <option value="1" selected>Medium Importance</option>
                        <option value="2">High Importance</option>
                    </select>
                    <select class="task_input full_width" name="urgency" id="urgency">
                        <option value="0">Low Urgency</option>
                        <option value="1" selected>Medium Urgency</option>
                        <option value="2">High Urgency</option>
                    </select>
                    <textarea class="task_input full_width" id="long_desc" name="long_desc" placeholder="Description"></textarea>
                    <div class="table full_width no_bottom">
                        <div class="table-cell no_bottom">
                            <input class="button label small_text no_bottom center" type="submit" name="action" value="Save">
                        </div>
                        <div class="table-cell no_bottom" onclick="hide();">
                            <input class="button label small_text no_bottom center" type="button" value="Cancel"></button>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="changes_made" value="0">
                {% csrf_token %}
            </form>
        </div>
    </div>
    {% for task in all_tasks %}
    <div id="{{ task.pk }}" class="backdrop">
        <div class="detailcontainer">
            <form action="{% url 'taskmaster:save' %}" method="POST">
                <input type="hidden" name="pk" id="pk" value="{{ task.pk }}">
                <div id="detail{{ task.pk }}" class="detail{% if task.importance == 2 %} high{% elif task.importance == 0 %} low{% else %} medium{% endif %}">
                    <input type="text" class="task_input full_width" id="short_desc{{ task.pk }}" name="short_desc" placeholder="Title" value="{{ task.short_desc }}" required>
                    <input type="date" class="task_input full_width no_bottom" id="due_date{{ task.pk }}" name="due_date" value="{{ task.due_date|date:'Y-m-d' }}" >
                    <input type="time" class="task_input full_width" id="due_time{{ task.pk }}" name="due_time" value="{{ task.due_time|time:'H:i' }}">
                    <select class="task_input no_bottom full_width" name="importance" id="importance{{ task.pk }}" onChange="change_importance({{ task.pk }});">
                        <option value="0"{% if task.importance == 0 %} selected{% endif %}>Low Importance</option>
                        <option value="1"{% if task.importance == 1 %} selected{% endif %}>Medium Importance</option>
                        <option value="2"{% if task.importance == 2 %} selected{% endif %}>High Importance</option>
                    </select>
                    <select class="task_input full_width" name="urgency" id="urgency{{ task.pk }}">
                        <option value="0"{% if task.urgency == 0 %} selected{% endif %}>Low Urgency</option>
                        <option value="1"{% if task.urgency == 1 %} selected{% endif %}>Medium Urgency</option>
                        <option value="2"{% if task.urgency == 2 %} selected{% endif %}>High Urgency</option>
                    </select>
                    <textarea class="task_input full_width" id="long_desc{{ task.pk }}" name="long_desc" placeholder="Description">{% if task.long_desc == Null %}{% else %}{{ task.long_desc }}{% endif %}</textarea>
                    <div class="table full_width no_bottom">
                        <div class="table-cell no_bottom">
                            <input class="button label small_text no_bottom center" type="submit" name="action" value="Save">
                        </div>
                        <div class="table-cell">
                            <input class="button label small_text no_bottom center" type="submit" name="action" value="Delete" onClick="return confirm('Are you sure you want to delete this task?');">
                        </div>
                        <div class="table-cell no_bottom" onclick="hide();">
                            <input class="button label small_text no_bottom center" type="button" value="Cancel"></button>
                        </div>
                    </div>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}

{% load static %}

<div id="body" class="overlay" style="background-image: url('{% static 'taskmaster/logo.png' %}');">
    <div class="title">Task Master</div>
    <div class="subtitle">An application from <a href="https://spiffindustries.com/">Spiff Industries</a></h2></div>
    <div class="links">
        <a class="buttonlink" href="{% url 'taskmaster:login' %}">
            <div id="login" class="button navigation">
                <div class="label normal_text">Login</div>
            </div>
        </a>
        <a class="buttonlink" href="{% url 'taskmaster:register' %}">
            <div id="register" class="button navigation">
                <div class="label normal_text">Register</div>
            </div>
        </a>
        <div>
            {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-dark{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/taskmaster/header.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Icons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
        <link rel="stylesheet" href="{% static 'taskmaster/style.css' %}">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'taskmaster/style.css' %}">
        <!-- Javascript -->
        <script src="{% static 'taskmaster/main.js' %}"></script>
        <script src="https://www.google.com/recaptcha/api.js?render={{ reCAPTCHA_site_key }}"></script>
        <script>
            grecaptcha.ready(function () {
                grecaptcha.execute('{{ reCAPTCHA_site_key }}', {action: 'validate_captcha'}).then(function (token) {
                    console.info("got token: " + token);
                    document.getElementById('g-recaptcha-response').value = token;
                });
            });
        </script>
        <title>Task Master</title>
    </head>
    <body>

        {% block content %}

        {% endblock %} 
      
    </body>
</html>

templates/taskmaster/login.html
{% extends "taskmaster/header.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
    <h1>Task Master</h1>
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="button label normal_text" style="float: left;" type="submit">Login</button>
        <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response">
        <input type="hidden" name="action" value="validate_captcha">
    </form>
    <p>Forgot your password? <a href="{% url 'taskmaster:password_reset' %}">Reset it here</a>.</p>
    <p>Don't have an account? <a href="{% url 'taskmaster:register' %}">Create an account</a>.</p>
    <div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-dark{% endif %}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

templates/taskmaster/register.html
{% extends "taskmaster/header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Task Master</h1>
    <h2>Register</h2>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="button label normal_text" style="float: left;" type="submit">Register</button>
        <input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response">
        <input type="hidden" name="action" value="validate_captcha">
	</form>
	<p>If you already have an account, <a href="{% url 'taskmaster:login' %}">login</a> instead.</p>
    <div>
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-dark{% endif %}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

templates/taskmaster/tasks.html
    <div class="task {% if task.importance == 0 %}low{% elif task.importance == 1 %}medium{% else %}high{% endif %}" id="task{{ task.pk }}">
        <input type="checkbox"{% if task.completed %} checked{% endif %} onchange="location.href='{% url 'taskmaster:toggle' task.id %}';">
        <div class="label" id="label{{ task.pk }}" data-value="{{ task.short_desc }}" onClick="expand('{{ task.pk }}');">
            &#8862; {{ task.short_desc }}
        </div>
        <div class="details" id="details{{ task.pk }}">
            {% if task.due_date != Null %}<b>Due: </b>{{ task.formatted_due_date }}{% if task.due_time != Null %} {{ task.due_time }}{% endif %}<br>{% endif %}
            {% if task.long_desc != Null %}{{ task.long_desc }}{% endif %}
            {% if task.due_date == Null and task.long_desc == Null %}No information{% endif %}
        </div>
        <div class="edit button" style="display: none;" id="edit{{ task.pk }}" onclick="show_task({{ task.pk }});">
            <div class="label small_text">Edit</div>
        </div>
    </div>